spring:
  data:
    redis:
      host: localhost
      port: 6380
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5438/book_db
    username: postgres
    password: postgres
    hikari:
      schema: book_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS book_schema
      connection-timeout: 10000

app:
  redis:
    enable: true
  cache:
    cache-names:
      - booksByCategory
      - booksByNameAndAuthor
    caches:
      booksByNameAndAuthor:
        expiry: 25s
      booksByCategory:
        expiry: 30s

