server:
  port: ${SOCKET_SERVER_PORT:8888}

logging:
  level:
    ROOT: INFO

app:
  path: ${TXT_FILE_PATH:src/main/resources/default-students.txt}

spring:
  profiles:
    active: ${PROFILE:init}
  main:
    web-application-type: none
