version: '3'
services:
  postgres:
    image: postgres:12.3
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_app_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql