spring:
  application:
    name: spring-kafka-order-service
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    orderTopic: "order-topic"
    orderStatusTopic: "order-status-topic"
    orderGroupId: "order-group-id"