spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5436/news_app_db
    username: postgres
    password: postgres
    hikari:
      schema: news_app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS news_app_schema
      connection-timeout: 10000


